Unit functional tests
siggwer/Bilemo pull request #4
Opened 2020-01-25 20:39 UTC by siggwer

2020-01-25 20:57 UTC, TBoileau requested changes

2020-01-25 20:57 UTC, TBoileau commented on .env.test
> +PANTHER_APP_ENV=panther
Attention, ici il attend le nom de l'environnement (`dev` ou `prod`), car quand tu lances tes tests avec Panther, il va donc simuler réellement l'ouverture d'un navigateur avec l'environnement

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/BrandTest.php
> +        }
Supprimer les try catch

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/BrandTest.php
> +    }
Supprimer la relation `OneToMany` car ne sera jamais utiliser (penser à supprimer l'attribut `inversedBy` dans `Product`)

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/BrandTest.php
> +        $this->user = new User();
Supprimer

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/BrandTest.php
> +    private $user;
Supprimer

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ClientTest.php
> +    private $user;
Supprimer

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ClientTest.php
> +        $this->user = new User();
Supprimer

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ClientTest.php
> +        }
Supprimer try catch

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ClientTest.php
> +    }
On a pas besoin de la relation OneToMany, donc on la supprime et ce test est inutile

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ProductTest.php
> +    private $user;
Supprimer

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ProductTest.php
> +        $this->user = new User();
Supprimer

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ProductTest.php
> +        }
Supprimer try catch

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ProductTest.php
> +        $this->assertNull($this->product->getReference());
Attention, on parle de la prop "name" et non "reference"
Pas besoin de tester si c'est null, donc on peut supprimer ce teswt

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ProductTest.php
> +    }
Inutile, on supprimer

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ProductTest.php
> +    }
Inutile, on supprimer

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ProductTest.php
> +    }
Inutile, on supprimer

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/ProductTest.php
> +    }
Inutile, on supprimer

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/UserTest.php
> +    private $product;
Inutile, on supprime

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/UserTest.php
> +        $this->product = new Product();
Inutile, on supprime

2020-01-25 20:57 UTC, TBoileau commented on tests/UnitTests/Entity/UserTest.php
> +        }
Supprimer try catch

2020-01-28 08:40 UTC, siggwer commented on .env.test
> +PANTHER_APP_ENV=panther
J'ai modifié l'environnement de Panther en mode développement. Je repasserai en mode prod une fois le projet entièrement finalisé voir le commit https://github.com/siggwer/Bilemo/commit/3901c874341ae5ceb3086ad8075c77003fc91e93.

2020-01-28 12:50 UTC, siggwer commented on tests/UnitTests/Entity/BrandTest.php
> +        }
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:50 UTC, siggwer commented on tests/UnitTests/Entity/BrandTest.php
> +    }
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:50 UTC, siggwer commented on tests/UnitTests/Entity/BrandTest.php
> +        $this->user = new User();
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:50 UTC, siggwer commented on tests/UnitTests/Entity/BrandTest.php
> +    private $user;
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ClientTest.php
> +    private $user;
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ClientTest.php
> +        $this->user = new User();
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ClientTest.php
> +        }
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ClientTest.php
> +    }
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ProductTest.php
> +    private $user;
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ProductTest.php
> +        $this->user = new User();
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ProductTest.php
> +        }
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ProductTest.php
> +        $this->assertNull($this->product->getReference());
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ProductTest.php
> +        $this->assertNull($this->product->getReference());
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ProductTest.php
> +    }
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ProductTest.php
> +    }
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:51 UTC, siggwer commented on tests/UnitTests/Entity/ProductTest.php
> +    }
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:52 UTC, siggwer commented on tests/UnitTests/Entity/ProductTest.php
> +    }
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:52 UTC, siggwer commented on tests/UnitTests/Entity/UserTest.php
> +    private $product;
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:52 UTC, siggwer commented on tests/UnitTests/Entity/UserTest.php
> +        $this->product = new Product();
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-28 12:52 UTC, siggwer commented on tests/UnitTests/Entity/UserTest.php
> +        }
Modification effectuée voir le commit 16bbcb286e51b5ad44312956dfe8609f9aa20e68.

2020-01-29 10:31 UTC, TBoileau requested changes

2020-01-29 10:31 UTC, TBoileau commented on src/Entity/Client.php
> -    }
Attention getRoles doit bien être implémenté

2020-01-29 10:31 UTC, TBoileau commented on src/Entity/Product.php
> -     * @ORM\JoinColumn(name="brand_id", referencedColumnName="id", onDelete="CASCADE", nullable=false)
Pourquoi avoir enlevé la relation ?

2020-01-29 10:31 UTC, TBoileau commented on src/Entity/User.php
> -     * @ORM\JoinColumn(name="client_id", referencedColumnName="id", onDelete="CASCADE", nullable=false)
Pourquoi avoir enlevé la relation ?

2020-01-30 10:48 UTC, siggwer commented on src/Entity/Client.php
> -    }
Modification effectuée voir le commit 9321966.

2020-01-30 10:48 UTC, siggwer commented on src/Entity/Product.php
> -     * @ORM\JoinColumn(name="brand_id", referencedColumnName="id", onDelete="CASCADE", nullable=false)
Modification effectuée voir le commit 9321966.

2020-01-30 10:48 UTC, siggwer commented on src/Entity/User.php
> -     * @ORM\JoinColumn(name="client_id", referencedColumnName="id", onDelete="CASCADE", nullable=false)
Modification effectuée voir le commit 9321966.

2020-02-04 19:50 UTC, TBoileau approved these changes

2020-02-04 19:50 UTC, merged