Security
siggwer/Bilemo pull request #8
Opened 2020-02-22 18:38 UTC by siggwer

Implement security

2020-03-06 20:02 UTC, TBoileau requested changes

2020-03-06 20:02 UTC, TBoileau commented on src/Controller/ProductController.php
> +     * )
A supprimer

2020-03-06 20:02 UTC, TBoileau commented on src/Controller/UserController.php
> +     * )
Supprimer

2020-03-06 20:02 UTC, TBoileau commented on src/Controller/ProductController.php
> +     *     @SWG\Schema(ref=@Model(type=App\Entity\Product::class, groups={"list_product"}))
https://github.com/zircote/swagger-php/issues/245#issuecomment-141076502

2020-03-06 20:02 UTC, TBoileau commented on src/Controller/ProductController.php
> +        Request $request
Supprimer et remplacer par l'injection d'un objet Product (utilisant iansi le ParamConverter)

2020-03-06 20:02 UTC, TBoileau commented on src/Controller/UserController.php
> +     *     @SWG\Schema(ref=@Model(type=App\Entity\User::class, groups={"list_user"}))
https://github.com/zircote/swagger-php/issues/245#issuecomment-141076502

2020-03-06 20:02 UTC, TBoileau commented on src/Controller/UserController.php
> +            Response::HTTP_NO_CONTENT, ['content-type' => 'application/json']);
Supprimer la serialization de l'user et return null

2020-03-06 20:02 UTC, TBoileau commented on src/DataFixtures/AppFixtures.php
> +}
Tu peux supprimer ce fichier du coup

2020-03-06 20:02 UTC, TBoileau commented on src/Security/UserVoter.php
> +//        throw new \LogicException('This code should not be reached!');
pense à supprimer le code mort

2020-03-09 12:58 UTC, siggwer commented on src/Controller/ProductController.php
> +     * )
Modifications effectuées voir le commit f442970.

2020-03-09 12:58 UTC, siggwer commented on src/Controller/UserController.php
> +     * )
Modifications effectuées voir le commit f442970.

2020-03-09 12:58 UTC, siggwer commented on src/Controller/ProductController.php
> +     *     @SWG\Schema(ref=@Model(type=App\Entity\Product::class, groups={"list_product"}))
Modifications effectuées voir le commit f442970.

2020-03-09 12:58 UTC, siggwer commented on src/Controller/ProductController.php
> +        Request $request
Modifications effectuées voir le commit f442970.

2020-03-09 12:58 UTC, siggwer commented on src/Controller/UserController.php
> +     *     @SWG\Schema(ref=@Model(type=App\Entity\User::class, groups={"list_user"}))
Modifications effectuées voir le commit f442970.

2020-03-09 12:58 UTC, siggwer commented on src/Controller/UserController.php
> +            Response::HTTP_NO_CONTENT, ['content-type' => 'application/json']);
Modifications effectuées voir le commit f442970.

2020-03-09 13:01 UTC, siggwer commented on src/DataFixtures/AppFixtures.php
> +}
Modifications effectuées voir le commit 00adf81.

2020-03-09 13:01 UTC, siggwer commented on src/Security/UserVoter.php
> +//        throw new \LogicException('This code should not be reached!');
Modifications effectuées voir le commit 00adf81.

2020-03-10 20:33 UTC, TBoileau approved these changes

2020-03-10 20:34 UTC, merged